apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liveapp
  namespace: liveapp
  annotations:
    cert-manager.io/issuer: "letsencrypt-liveapp"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - liveapp.example.com
    secretName: liveapp-tls
  rules:
  - host: liveapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: liveapp
            port:
              name: http