import {
  ClusterAdapterWithHeartbeat,
  ClusterMessage,
  ClusterResponse,
  MessageType,
  Offset,
  ServerId,
} from "socket.io-adapter";
import { encode } from "@msgpack/msgpack";

import { createLogger } from "./logger";
import type { MeshContext } from "./mesh-context";

const log = createLogger("adapter");

const RESPONSE_TYPES = new Set<MessageType>([
  MessageType.FETCH_SOCKETS_RESPONSE,
  MessageType.SERVER_SIDE_EMIT_RESPONSE,
  MessageType.BROADCAST_CLIENT_COUNT,
  MessageType.BROADCAST_ACK,
]);

/**
 * Returns true if the given message type is a response (sent point-to-point
 * to the requester) rather than a broadcast-style cluster message.
 */
export function isResponseType(type: MessageType): boolean {
  return RESPONSE_TYPES.has(type);
}

/**
 * The Socket.IO adapter that uses a peer-to-peer WebSocket mesh as the
 * transport. All multi-server semantics (broadcast, broadcastWithAck,
 * fetchSockets, socketsJoin/Leave, disconnectSockets, serverSideEmit,
 * heartbeats, request/response correlation) are inherited from
 * {@link ClusterAdapterWithHeartbeat}; this subclass only forwards messages
 * over the mesh transport.
 */
export class MeshAdapter extends ClusterAdapterWithHeartbeat {
  /** Exposed for the context router. */
  public get serverUid(): ServerId {
    return this.uid;
  }

  constructor(
    nsp: any,
    private readonly ctx: MeshContext,
    opts: { heartbeatInterval?: number; heartbeatTimeout?: number }
  ) {
    super(nsp, opts);
    // Override the random uid generated by ClusterAdapter so that every adapter
    // (across namespaces) on the same server shares the context's uid. The mesh
    // transport routes peers by this uid, so they must agree.
    (this as unknown as { uid: ServerId }).uid = ctx.uid;
    ctx.registerAdapter(nsp.name, this);
    log("[%s] adapter ready for namespace %s", this.uid, nsp.name);
  }

  /**
   * Called by the context when a frame addressed to this adapter's namespace
   * arrives from a peer. The base class's onMessage handles all message
   * types, including dispatching responses to onResponse internally.
   */
  public handleInbound(message: ClusterMessage | ClusterResponse): void {
    if (isResponseType(message.type)) {
      this.onResponse(message as ClusterResponse);
    } else {
      this.onMessage(message as ClusterMessage);
    }
  }

  protected async doPublish(message: ClusterMessage): Promise<Offset> {
    const body = encode(message);
    const buf = Buffer.from(body.buffer, body.byteOffset, body.byteLength);
    this.ctx.transport.sendMeshToAll(buf, message.type);
    return "";
  }

  protected async doPublishResponse(
    requesterUid: ServerId,
    response: ClusterResponse
  ): Promise<void> {
    const body = encode(response);
    const buf = Buffer.from(body.buffer, body.byteOffset, body.byteLength);
    this.ctx.transport.sendMeshToPeer(requesterUid, buf, response.type);
  }

  override async fetchSockets(opts: any): Promise<any[]> {
    const stop = this.ctx.metrics.requestStarted("fetchSockets");
    try {
      return await super.fetchSockets(opts);
    } finally {
      stop();
    }
  }

  override async serverSideEmit(packet: any[]): Promise<any> {
    const stop = this.ctx.metrics.requestStarted("serverSideEmit");
    try {
      return await super.serverSideEmit(packet);
    } finally {
      stop();
    }
  }

  override broadcastWithAck(
    packet: any,
    opts: any,
    clientCountCallback: (clientCount: number) => void,
    ack: (...args: any[]) => void
  ): void {
    const stop = this.ctx.metrics.requestStarted("broadcastWithAck");
    let stopped = false;
    const stopOnce = () => {
      if (stopped) return;
      stopped = true;
      stop();
    };
    super.broadcastWithAck(
      packet,
      opts,
      clientCountCallback,
      (...args: any[]) => {
        try {
          ack(...args);
        } finally {
          // Ack fires once per responding server; we stop the timer on the
          // first invocation to measure time-to-first-response. The base
          // class will keep invoking `ack` for subsequent peers.
          stopOnce();
        }
      }
    );
  }

  override close(): void {
    log("[%s] closing adapter for namespace %s", this.uid, this.nsp.name);
    super.close();
    this.ctx.unregisterAdapter(this.nsp.name);
  }
}
